# Base directory â€“ where commands run and publish/functions are relative to
base = "NETLIFY"  # Set base to NETLIFY folder

# Build settings
[build]
  command = "npm install && npm run build"
  publish = "out"  # Next.js static export output

# Functions directory
[functions]
  directory = "netlify/functions"

# Redirect all traffic to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
