# Base directory â€“ where commands run and publish/functions are relative to
base = "NETLIFY"

# Build settings
[build]
  command = "mv ../package.json ../package.json.bak && npm install && npm run build && mv ../package.json.bak ../package.json"
  publish = "out"

# Functions directory
[functions]
  directory = "netlify/functions"

# Redirect all traffic to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
